name: SonarCloud Scan

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to analyze'
        required: true
        default: 'main'

jobs:
  sonarqube:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK (if you're using Java, adjust as needed for your tech stack)
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # or the version you're using

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          args: |
            -Dsonar.projectKey=Mai_EFAT          # Project Key
            -Dsonar.projectName=jenkins-demo     # Project Name
            -Dsonar.branch.name=${{ github.event.inputs.branch }}  # Branch to analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Set the token in the environment variable


    # # Step 3: Run Trivy vulnerability scan for Docker image
    # - name: Install Trivy and run vulnerability scan
    #   uses: aquasecurity/trivy-action@v0.5.0
    #   with:
    #     image-ref: your-docker-image-name:latest  # Specify your Docker image name here
    #   env:
    #     TRIVY_SEVERITY: HIGH,CRITICAL  # You can set severity levels for the scan

    # # Step 4: Run Fortify static code analysis
    # - name: Install Fortify and run scan
    #   run: |
    #     curl -O https://fortify.com/downloads/fortify-sca-latest.zip
    #     unzip fortify-sca-latest.zip -d /opt/fortify
    #     /opt/fortify/bin/fortify-sca -b build_id -source source_path -scan
    #   env:
    #     FORTIFY_USERNAME: ${{ secrets.FORTIFY_USERNAME }}
    #     FORTIFY_PASSWORD: ${{ secrets.FORTIFY_PASSWORD }}
